### ISSUE TITLE
File to import not found or unreadable: ~Assets/css/vars.

### ISSUE THREAD

**Issue by ujinyoung** [PPIO/pp.io#1]
I command ```npm run start```

but get some errors, ```File to import not found or unreadable: ~Assets/css/vars.``` at all scss files.

so I change to url(~Assets/css/vars),  and get another errors, ```Undefined variable: "$theme-color```

**Comment by GauravWalia19** [comment]
I am also getting the same errors. Here is the error log:

![Screenshot from 2019-06-25 15-25-56](https://user-images.githubusercontent.com/29369199/60089298-cd157900-975d-11e9-92ba-30b5edd1c43a.png)

![Screenshot from 2019-06-25 15-26-08](https://user-images.githubusercontent.com/29369199/60089314-d30b5a00-975d-11e9-900d-ae4dbb07cdfa.png)

**Comment by ChangMM** [comment]
change `~Assets/css/vars` to `~ assets/css/vars`
